/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox Deidentifier API
 * The OpenAPI specification implemented by NLP Sandbox PHI Deidentifiers. # Overview TBA 
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    DeidentifyRequest,
    DeidentifyRequestFromJSON,
    DeidentifyRequestToJSON,
    DeidentifyResponse,
    DeidentifyResponseFromJSON,
    DeidentifyResponseToJSON,
} from '../models';

export interface CreateDeidentifiedNotesRequest {
    deidentifyRequest?: DeidentifyRequest;
}

/**
 * 
 */
export class DeidentifiedNotesApi extends runtime.BaseAPI {

    /**
     * Returns the deidentified note
     * Deidentify a clinical note
     */
    async createDeidentifiedNotesRaw(requestParameters: CreateDeidentifiedNotesRequest): Promise<runtime.ApiResponse<DeidentifyResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/deidentifiedNotes`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeidentifyRequestToJSON(requestParameters.deidentifyRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => DeidentifyResponseFromJSON(jsonValue));
    }

    /**
     * Returns the deidentified note
     * Deidentify a clinical note
     */
    async createDeidentifiedNotes(requestParameters: CreateDeidentifiedNotesRequest): Promise<DeidentifyResponse> {
        const response = await this.createDeidentifiedNotesRaw(requestParameters);
        return await response.value();
    }

}
