/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox Deidentifier API
 * The OpenAPI specification implemented by NLP Sandbox PHI Deidentifiers. # Overview TBA 
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    HealthCheck,
    HealthCheckFromJSON,
    HealthCheckToJSON,
} from '../models';

/**
 * 
 */
export class HealthCheckApi extends runtime.BaseAPI {

    /**
     * Get information about the health of the service
     * Get health check information
     */
    async getHealthCheckRaw(): Promise<runtime.ApiResponse<HealthCheck>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/healthCheck`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthCheckFromJSON(jsonValue));
    }

    /**
     * Get information about the health of the service
     * Get health check information
     */
    async getHealthCheck(): Promise<HealthCheck> {
        const response = await this.getHealthCheckRaw();
        return await response.value();
    }

}
