/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox Deidentifier API
 * The OpenAPI specification implemented by NLP Sandbox PHI Deidentifiers. # Overview TBA 
 *
 * The version of the OpenAPI document: 0.2.2
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TextAnnotation,
    TextAnnotationFromJSON,
    TextAnnotationFromJSONTyped,
    TextAnnotationToJSON,
} from './';

/**
 * A person name annotation in a text
 * @export
 * @interface TextPersonNameAnnotation
 */
export interface TextPersonNameAnnotation extends TextAnnotation {
}

export function TextPersonNameAnnotationFromJSON(json: any): TextPersonNameAnnotation {
    return TextPersonNameAnnotationFromJSONTyped(json, false);
}

export function TextPersonNameAnnotationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextPersonNameAnnotation {
    return json;
}

export function TextPersonNameAnnotationToJSON(value?: TextPersonNameAnnotation | null): any {
    return value;
}


