/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox Deidentifier API
 * The OpenAPI specification implemented by NLP Sandbox PHI Deidentifiers. # Overview TBA 
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ResourceSource,
    ResourceSourceFromJSON,
    ResourceSourceFromJSONTyped,
    ResourceSourceToJSON,
} from './';

/**
 * The source of an annotation record
 * @export
 * @interface AnnotationSource
 */
export interface AnnotationSource {
    /**
     * 
     * @type {ResourceSource}
     * @memberof AnnotationSource
     */
    resourceSource?: ResourceSource;
}

export function AnnotationSourceFromJSON(json: any): AnnotationSource {
    return AnnotationSourceFromJSONTyped(json, false);
}

export function AnnotationSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnotationSource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resourceSource': !exists(json, 'resourceSource') ? undefined : ResourceSourceFromJSON(json['resourceSource']),
    };
}

export function AnnotationSourceToJSON(value?: AnnotationSource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resourceSource': ResourceSourceToJSON(value.resourceSource),
    };
}


