/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox Deidentifier API
 * The OpenAPI specification implemented by NLP Sandbox PHI Deidentifiers. # Overview TBA 
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Configuration for the "date offset" strategy. E.g. "John Smith visited on 1 January 2020" -> "John Smith visited on 29 October 2025". Note, can only be set with the "text_date" annotation type.
 * @export
 * @interface DeidentificationConfigDeidentificationStrategyDateOffsetConfig
 */
export interface DeidentificationConfigDeidentificationStrategyDateOffsetConfig {
    /**
     * Number of days by which to offset annotated dates.
     * @type {number}
     * @memberof DeidentificationConfigDeidentificationStrategyDateOffsetConfig
     */
    offsetDays?: number;
}

export function DeidentificationConfigDeidentificationStrategyDateOffsetConfigFromJSON(json: any): DeidentificationConfigDeidentificationStrategyDateOffsetConfig {
    return DeidentificationConfigDeidentificationStrategyDateOffsetConfigFromJSONTyped(json, false);
}

export function DeidentificationConfigDeidentificationStrategyDateOffsetConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeidentificationConfigDeidentificationStrategyDateOffsetConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offsetDays': !exists(json, 'offsetDays') ? undefined : json['offsetDays'],
    };
}

export function DeidentificationConfigDeidentificationStrategyDateOffsetConfigToJSON(value?: DeidentificationConfigDeidentificationStrategyDateOffsetConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offsetDays': value.offsetDays,
    };
}


