/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox Deidentifier API
 * The OpenAPI specification implemented by NLP Sandbox PHI Deidentifiers. # Overview TBA 
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represents the health of a service
 * @export
 * @interface HealthCheck
 */
export interface HealthCheck {
    /**
     * Indicates whether the service status is acceptable or not
     * @type {string}
     * @memberof HealthCheck
     */
    status: HealthCheckStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum HealthCheckStatusEnum {
    Pass = 'pass',
    Fail = 'fail',
    Warn = 'warn'
}

export function HealthCheckFromJSON(json: any): HealthCheck {
    return HealthCheckFromJSONTyped(json, false);
}

export function HealthCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheck {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function HealthCheckToJSON(value?: HealthCheck | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}


