/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox Deidentifier API
 * The OpenAPI specification implemented by NLP Sandbox PHI Deidentifiers. # Overview TBA 
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * License (license keyword used by GitHub)
 * @export
 * @enum {string}
 */
export enum License {
    Afl30 = 'afl-3.0',
    Apache20 = 'apache-2.0',
    Artistic20 = 'artistic-2.0',
    Bsl10 = 'bsl-1.0',
    Bsd2Clause = 'bsd-2-clause',
    Bsd3Clause = 'bsd-3-clause',
    Bsd3ClauseClear = 'bsd-3-clause-clear',
    Cc = 'cc',
    Cc010 = 'cc0-1.0',
    CcBy40 = 'cc-by-4.0',
    CcBySa40 = 'cc-by-sa-4.0',
    Wtfpl = 'wtfpl',
    Ecl20 = 'ecl-2.0',
    Epl10 = 'epl-1.0',
    Epl20 = 'epl-2.0',
    Eupl11 = 'eupl-1.1',
    Agpl30 = 'agpl-3.0',
    Gpl = 'gpl',
    Gpl20 = 'gpl-2.0',
    Gpl30 = 'gpl-3.0',
    Lgpl = 'lgpl',
    Lgpl21 = 'lgpl-2.1',
    Lgpl30 = 'lgpl-3.0',
    Isc = 'isc',
    Lppl13c = 'lppl-1.3c',
    MsPl = 'ms-pl',
    Mit = 'mit',
    Mpl20 = 'mpl-2.0',
    Osl30 = 'osl-3.0',
    Postgresql = 'postgresql',
    Ofl11 = 'ofl-1.1',
    Ncsa = 'ncsa',
    Unlicense = 'unlicense',
    Zlib = 'zlib'
}

export function LicenseFromJSON(json: any): License {
    return LicenseFromJSONTyped(json, false);
}

export function LicenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): License {
    return json as License;
}

export function LicenseToJSON(value?: License | null): any {
    return value as any;
}

