/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox Deidentifier API
 * The OpenAPI specification implemented by NLP Sandbox PHI Deidentifiers. # Overview TBA 
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TextDateAnnotationAllOf
 */
export interface TextDateAnnotationAllOf {
    /**
     * Date format (ISO 8601)
     * @type {string}
     * @memberof TextDateAnnotationAllOf
     */
    dateFormat?: string;
}

export function TextDateAnnotationAllOfFromJSON(json: any): TextDateAnnotationAllOf {
    return TextDateAnnotationAllOfFromJSONTyped(json, false);
}

export function TextDateAnnotationAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextDateAnnotationAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dateFormat': !exists(json, 'dateFormat') ? undefined : json['dateFormat'],
    };
}

export function TextDateAnnotationAllOfToJSON(value?: TextDateAnnotationAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dateFormat': value.dateFormat,
    };
}


