/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox Deidentifier API
 * The OpenAPI specification implemented by NLP Sandbox PHI Deidentifiers. # Overview TBA 
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Tool,
    ToolFromJSON,
    ToolFromJSONTyped,
    ToolToJSON,
} from './';

/**
 * A list of tool dependencies
 * @export
 * @interface ToolDependencies
 */
export interface ToolDependencies {
    /**
     * A list of tools
     * @type {Array<Tool>}
     * @memberof ToolDependencies
     */
    toolDependencies?: Array<Tool>;
}

export function ToolDependenciesFromJSON(json: any): ToolDependencies {
    return ToolDependenciesFromJSONTyped(json, false);
}

export function ToolDependenciesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolDependencies {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'toolDependencies': !exists(json, 'toolDependencies') ? undefined : ((json['toolDependencies'] as Array<any>).map(ToolFromJSON)),
    };
}

export function ToolDependenciesToJSON(value?: ToolDependencies | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'toolDependencies': value.toolDependencies === undefined ? undefined : ((value.toolDependencies as Array<any>).map(ToolToJSON)),
    };
}


